
import java.awt.event.KeyEvent;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class AplikasiKonversiSuhu extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiKonversiSuhu
     */
    public AplikasiKonversiSuhu() {
        initComponents();
        ButtonGroup group = new ButtonGroup();
        group.add(jRadio1);
        group.add(jRadio2);
        group.add(jRadio3);
        group.add(jRadio4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textFieldInput = new javax.swing.JTextField();
        comboBoxScale = new javax.swing.JComboBox<>();
        buttonConvert = new javax.swing.JButton();
        jRadio1 = new javax.swing.JRadioButton();
        textFieldResult = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jRadio2 = new javax.swing.JRadioButton();
        jRadio3 = new javax.swing.JRadioButton();
        jRadio4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPanel1KeyTyped(evt);
            }
        });

        jLabel1.setText("Masukkan Suhu");

        textFieldInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldInputActionPerformed(evt);
            }
        });
        textFieldInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldInputKeyTyped(evt);
            }
        });

        comboBoxScale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit", "Reamur", "Kelvin" }));
        comboBoxScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxScaleActionPerformed(evt);
            }
        });

        buttonConvert.setText("Konversi");
        buttonConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConvertActionPerformed(evt);
            }
        });

        jRadio1.setSelected(true);
        jRadio1.setText("Celcius To Fahrenheit");
        jRadio1.setToolTipText("");
        jRadio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio1ActionPerformed(evt);
            }
        });

        textFieldResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldResultActionPerformed(evt);
            }
        });

        jLabel2.setText("Hasil Konversi");

        jRadio2.setText("Fahrenheit To Celcius");
        jRadio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio2ActionPerformed(evt);
            }
        });

        jRadio3.setText("Celcius To Reamur");
        jRadio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio3ActionPerformed(evt);
            }
        });

        jRadio4.setText("Fahrenheti To Reamur");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comboBoxScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadio2)
                            .addComponent(jRadio1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadio4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadio3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldResult, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxScale, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldInput)
                    .addComponent(buttonConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadio1)
                    .addComponent(jRadio3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadio2)
                    .addComponent(jRadio4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldResult, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldResultActionPerformed

    private void jRadio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio1ActionPerformed
    jRadio1.addActionListener(e -> System.out.println());    // TODO add your handling code here:
    }//GEN-LAST:event_jRadio1ActionPerformed

    private void buttonConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConvertActionPerformed
    try {
        // Mengambil nilai suhu yang dimasukkan oleh pengguna
        String inputText = textFieldInput.getText();

        // Pengecekan jika input kosong
        if (inputText.isEmpty()) {
            textFieldResult.setText("Masukkan suhu yang valid!");
            return; // Menghentikan proses konversi jika input kosong
        }

        // Mengonversi input menjadi angka
        double inputSuhu = Double.parseDouble(inputText);

        // Pengecekan jika suhu terlalu rendah (di bawah -273.15°C atau 0 Kelvin)
        if (inputSuhu < -273.15) {  // Suhu lebih rendah dari -273.15°C
            textFieldResult.setText("Suhu terlalu rendah!");
            return; // Menghentikan proses jika suhu terlalu rendah
        }

        // Lakukan konversi berdasarkan input yang valid
        String selectedScale = (String) comboBoxScale.getSelectedItem();  // Pilihan skala suhu
        double hasilKonversi = 0.0;

        // Mengecek arah konversi yang dipilih dan melakukan konversi berdasarkan skala suhu yang dipilih
        if ("Celsius".equals(selectedScale)) {
            if (jRadio1.isSelected()) {
                hasilKonversi = (inputSuhu * 9 / 5) + 32; // Rumus Celsius ke Fahrenheit
            } else if (jRadio3.isSelected()) {
                hasilKonversi = inputSuhu * 4 / 5; // Rumus Celsius ke Reamur
            } else if (jRadio2.isSelected()) {
                hasilKonversi = inputSuhu + 273.15; // Celsius ke Kelvin
            }
        } else if ("Fahrenheit".equals(selectedScale)) {
            if (jRadio2.isSelected()) {
                hasilKonversi = (inputSuhu - 32) * 5 / 9; // Rumus Fahrenheit ke Celsius
            } else if (jRadio4.isSelected()) {
                hasilKonversi = (inputSuhu - 32) * 4 / 9; // Rumus Fahrenheit ke Reamur
            } else if (jRadio2.isSelected()) {
                hasilKonversi = ((inputSuhu - 32) * 5 / 9) + 273.15; // Fahrenheit ke Kelvin
            }
        } else if ("Reamur".equals(selectedScale)) {
            if (jRadio3.isSelected()) {
                hasilKonversi = inputSuhu * 4 / 5; // Celsius ke Reamur
            } else if (jRadio4.isSelected()) {
                hasilKonversi = (inputSuhu - 32) * 4 / 9; // Fahrenheit ke Reamur
            } else if (jRadio1.isSelected()) {
                hasilKonversi = (inputSuhu * 9 / 5) + 32; // Reamur ke Fahrenheit
            }
        }

        // Menampilkan hasil konversi di textFieldResult
        textFieldResult.setText(String.valueOf(hasilKonversi));

    } catch (NumberFormatException e) {
        textFieldResult.setText("Masukkan suhu yang valid!"); // Jika input bukan angka
    }    // TODO add your handling code here:
    }//GEN-LAST:event_buttonConvertActionPerformed

    private void jRadio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio3ActionPerformed

    private void textFieldInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldInputActionPerformed

    private void jPanel1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyTyped

    private void textFieldInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldInputKeyTyped
    char karakter = evt.getKeyChar();
    // Memeriksa apakah karakter bukan digit dan bukan karakter kontrol (backspace, delete, dll.)
    if (!Character.isDigit(karakter) && karakter != KeyEvent.VK_BACK_SPACE && karakter != KeyEvent.VK_DELETE) {
        evt.consume();
        JOptionPane.showMessageDialog(this, "Masukkan hanya angka!", "Error", JOptionPane.ERROR_MESSAGE);
    }    // TODO add your handling code here:
    }//GEN-LAST:event_textFieldInputKeyTyped

    private void comboBoxScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxScaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxScaleActionPerformed

    private void jRadio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio2ActionPerformed
    jRadio2.addActionListener(e -> System.out.println("Pilihan 1 dipilih"));    // TODO add your handling code here:
    }//GEN-LAST:event_jRadio2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiKonversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConvert;
    private javax.swing.JComboBox<String> comboBoxScale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadio1;
    private javax.swing.JRadioButton jRadio2;
    private javax.swing.JRadioButton jRadio3;
    private javax.swing.JRadioButton jRadio4;
    private javax.swing.JTextField textFieldInput;
    private javax.swing.JTextField textFieldResult;
    // End of variables declaration//GEN-END:variables
}
